### ISSUE TITLE
Preview app login serves 400

### ISSUE THREAD

**Issue by JasonEtco** [planetscale/beam#44]
Hello ~T~ Beam! I went to check out the preview site listed in this repo's description (http://beam.preview.planetscale.com/) and hit <kbd>Sign in with Okta</kbd> - I get this:

![image](https://user-images.githubusercontent.com/10660468/155436245-ab1fa7f9-f98c-41b0-92c9-6bdbf831a2da.png)

Presumably y'all meant for the public, preview deployment to use GitHub auth? Either way, I don't think that error is what you're expecting, so flagging! 🐛

**Comment by jasonlong** [comment]
I've deleted that link from the repo description about 8 times now and it keeps reappearing. It must be something the Vercel integration is doing on deploy. If so, I'm assuming that behavior can be disabled.

**Comment by jasonlong** [comment]
I'm still looking into whether this auto-update feature can be disabled when Vercel deploys, but for now, I've updated the URL and will 🤞🏼 that future deploys don't overwrite it.
