### ISSUE TITLE
Show the content of a post when notifying Slack

### ISSUE THREAD

**Issue by marissamarym** [planetscale/beam#47]
# Description
Show the content of a post in the Slack message when notifying a Slack channel.

<img width="565" alt="Screen Shot 2022-02-24 at 5 09 30 PM" src="https://user-images.githubusercontent.com/1459660/155616783-98600b54-d77a-4090-8884-b8994925b735.png">

## Example
Here is an example post on Beam:

<img width="879" alt="Screen Shot 2022-02-24 at 5 10 08 PM" src="https://user-images.githubusercontent.com/1459660/155616006-15683f44-2cf8-46c7-a562-06d3facb4a43.png">

### Current behaviour of the Slack notification
Shows the link, title, and author
<img width="562" alt="Screen Shot 2022-02-24 at 5 09 20 PM" src="https://user-images.githubusercontent.com/1459660/155616026-d46362e8-abbd-488f-a428-c2155441f61c.png">

### Proposed behaviour of the Slack notification
Shows the link, title, author, and content
<img width="565" alt="Screen Shot 2022-02-24 at 5 09 30 PM" src="https://user-images.githubusercontent.com/1459660/155616147-5d0c88dc-84c0-41f8-abbb-5ebb0110e9ad.png">

# Possible solution
Using the https://github.com/instantish/mack package to convert markdown to Slack blocks.

Trade-offs: it adds another dependency, Slack messages will take up more vertical space in the channel.

Alternatives: just show the first few lines of text with an ellipsis, or just preview the images.

**Comment by jasonlong** [comment]
Showing the same snippet that is shown on the index page could be reasonable but I'm not in favor of rendering the whole post in Slack. This feature is really meant to just be a notification to let you know that a new post has been published.
