### ISSUE TITLE
Dockerize it

### ISSUE THREAD

**Issue by geekedtv** [planetscale/beam#51]
Any plans to dockerize this app?

**Comment by bogdansoare** [comment]
No plans for the near future, but since Beam uses Next.js, you can use the [Next.js docs](https://nextjs.org/docs/deployment#docker-image) as guidance, where you can find a [Dockerfile](https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile).

**Comment by geekedtv** [comment]
No plansy no usey for mesy,
