### ISSUE TITLE
Error logging in

### ISSUE THREAD

**Issue by Daniellop1** [planetscale/beam#56]
Hey, I'm triying to login to my Beam instance but this error shows (https://beam.daniellop.me/sign-in?callbackUrl=https://beam.daniellop.me/sign-in?callbackUrl=https://beam.daniellop.me/&error=Callback)

**Comment by bogdansoare** [comment]
Hey @Daniellop1, could you please share the error that you are getting on your next server?

**Comment by Daniellop1** [comment]
I have looked at the vercel error page and I don't have any and in the chrome developer console either.

**Comment by IAmLuisJ** [comment]
I would double check the callback URL you have setup. For example if you are using GitHub Auth, in the OAuth app settings you should set something like

Authorization callback URL:
https://beam.daniellop.me/api/auth/callback/github

That should get your user signed in.

**Comment by Daniellop1** [comment]
Hey, I have configured okta as a provider and this is the configuration I have set in my admin panel.

<img width="689" alt="Captura de Pantalla 2022-03-28 a la(s) 8 13 56 a m" src="https://user-images.githubusercontent.com/44546966/160337102-7185986e-3742-4998-8d9c-ed7b28d074c9.png">

**Comment by bogdansoare** [comment]
@Daniellop1 unfortunately without some logs from your server it's hard to figure out what is the issue. 
Next-auth has some pretty good errors on your server https://next-auth.js.org/errors#server

**Comment by juliozengcheil** [comment]
hey @Daniellop1 i have the same problem with github aoth, in dev, i visit `localhost:3000` it redirect me to `http://localhost:3000/sign-in?callbackUrl=http://localhost:3000/` and when i click `Signin with Github` it redirectme same page but extended url repeated `https://some.domaing.cloud/sign-in?callbackUrl=https://some.domain.cloud/sign-in?callbackUrl=https://some.domain.cloud/sign-in?callbackUrl=https://some.domain.cloud/sign-in?callbackUrl=https://some.domain.cloud/&error=Callback&error=OAuthCallback&error=OAuthCallback&error=Callback`

**Comment by Daniellop1** [comment]
> hey @Daniellop1 i have the same problem with github aoth, in dev, i visit `localhost:3000` it redirect me to `http://localhost:3000/sign-in?callbackUrl=http://localhost:3000/` and when i click `Signin with Github` it redirectme same page but extended url repeated `https://some.domaing.cloud/sign-in?callbackUrl=https://some.domain.cloud/sign-in?callbackUrl=https://some.domain.cloud/sign-in?callbackUrl=https://some.domain.cloud/sign-in?callbackUrl=https://some.domain.cloud/&error=Callback&error=OAuthCallback&error=OAuthCallback&error=Callback`

Yeah, thats exactly what happens to me. But with okta and github.

**Comment by juliozengcheil** [comment]
> @Daniellop1 unfortunately without some logs from your server it's hard to figure out what is the issue. Next-auth has some pretty good errors on your server https://next-auth.js.org/errors#server

the error i get in the url params are mostly error?error=Callback, here a screenshot of what the network receive

![image](https://user-images.githubusercontent.com/102690495/161091005-4fcb18da-0bca-46e1-bd99-53520b8f36d9.png)

**Comment by bogdansoare** [comment]
Without some server logs, or without a reproducible demo, it's hard to debug this.
Please make sure to have the proper configuration for Okta/GitHub.

**Comment by Daniellop1** [comment]
> Without some server logs, or without a reproducible demo, it's hard to debug this.
> Please make sure to have the proper configuration for Okta/GitHub.

Hey, I've created a test account for my instance (beam.daniellop.me)

Mail: test@daniellop.me
Pass: Demoaccount1.

**Comment by djakish** [comment]
I had the same issue, it got it fixed after i specified `NEXTAUTH_URL`

**Comment by Daniellop1** [comment]
I have found this error that might be helpful in finding the problem.
![Captura de Pantalla 2022-05-29 a la(s) 2 45 13 p m](https://user-images.githubusercontent.com/44546966/170869193-eb1d8f06-958f-47a3-b662-dc4b250d2f0d.png)

**Comment by bogdansoare** [comment]
@Daniellop1 could you please double-check that the database has the correct schema after you've run `npx prisma db push`?

**Comment by jgreet** [comment]
Assuming you're using a PlanetScale database, you'll see that Prisma error if you attempt to make a schema change (like creating a table) to a production branch directly.

https://docs.planetscale.com/concepts/branching#development-and-production-branches

A couple of options here:
- Start over with a new database and don't promote the `main` branch to production status until after you've got the initial schema set up and the application is running
- Create a branch from your existing `main`, connect your local dev environment to this new development branch, `npx prisma db push` to set up the schema in the development branch, deploy your changes to `main`. This is the workflow you'll use to apply any future schema changes to the database and is described in more detail in the doc linked above.

**Comment by Daniellop1** [comment]
I've found the error. You can't use beam with a deployed branch. Thanks for everything.
