### ISSUE TITLE
Single, double quotes, and profile links are displayed badly in Slack messages

### ISSUE THREAD

**Issue by piki** [planetscale/beam#72]
When Beam posts to Slack, single quotes are displayed as `&#39;`, double quotes are displayed as `&quot;`, and links to a user's profile are displayed in `<>` angle brackets.  All of these display fine on Beam web pages.
<img width="459" alt="Screen Shot 2022-10-18 at 2 01 06 PM" src="https://user-images.githubusercontent.com/3660033/196510045-6a9806f3-6e21-4c55-af6a-849ebb558e69.png">

<img width="667" alt="Screen Shot 2022-10-18 at 2 02 12 PM" src="https://user-images.githubusercontent.com/3660033/196510060-d11bcd6e-0d0a-449c-b8bd-0be36dec8961.png">

Looks like something is getting lost in the SQL -> markdown -> blocks -> POST [pipeline](https://github.com/planetscale/beam/blob/main/lib/slack.ts#L14-L24).

**Comment by jgreet** [comment]
Slack wants you to escape specific controls characters, `&`, `<`, and `>`:

https://api.slack.com/reference/surfaces/formatting#escaping

But markdownToBlocks from [mack](https://github.com/tryfabric/mack) seems to HTML entity-encode more than just those three. Didn't see an option to disable that behavior.

**Comment by mscoutermarsh** [comment]
Fixed the quotes. Profile links are probably still broken. We will see.

Closing this because it will feel satisfying
