### ISSUE TITLE
Setup Help

### ISSUE THREAD

**Issue by C-EO** [planetscale/beam#84]
I'm kinda new MySQL Databases

As I scrolled through the web, I came across this project and thought it would be useful for my company

thing is, i did all the other steps in the setup correctly, and i need help for the PlanetScale part

@jasonlong  please help

**Comment by jasonlong** [comment]
@C-EO What part are you stuck on?

**Comment by C-EO** [comment]
@jasonlong I was stuck on pushing the schema changes

But now I think I have found a work around that could be useful to other Beam users

**Comment by C-EO** [comment]
Since I didn't want to install the `pscale` cli and `mysql-client` I used [Replit](https://repl.it) to do the database bit of it.

### Resources:

- [PlanetScale Docs (Prisma setup)](https://planetscale.com/docs/tutorials/prisma-quickstart)
- [My Replit project](https://replit.com/@C-EO/pscale) -- for those who want to use my way

I really think this could be helpful to other Beam users especially those who don't want to hastle with ins

**Comment by C-EO** [comment]
Could I document my way as a backup to the ways PlanetScale is providing in this repo?
